account:
  uin: 123
  password: ""
  encrypt: false
  status: 0
  relogin:
    delay: 3
    interval: 3
    max-times: 0
  use-sso-address: true
heartbeat:
  interval: 5
message:
  post-format: array
  ignore-invalid-cqcode: false
  force-fragment: false
  fix-url: false
  proxy-rewrite: ""
  report-self-message: false
  remove-reply-at: false
  extra-reply-data: false
output:
  log-level: warn
  debug: false
default-middlewares: &default
  access-token: ""
  filter: ""
  rate-limit:
    enabled: false
    frequency: 1
    bucket: 1
database:
  leveldb:
    enable: true
servers:
  - http:
    disabled: true
    host: 127.0.0.1
    port: 5700
    timeout: 5
    middlewares:
      <<: *default
    post:
      - url: ""
        secret: ""
  - ws:
    disabled: true
    host: 127.0.0.1
    port: 6700
    middlewares:
      <<: *default
  - ws-reverse:
    disabled: true
    universal: ""
    reconnect-interval: 3000
    middlewares:
      <<: *default
